{% if spec.definitions.appwriteException.errorTypes|length > 0 %}
const assert = require('assert');
const { ErrorType } = require('../lib/exception.js');

try {
{% for error in spec.definitions.appwriteException.errorTypes %}
	assert.strictEqual(ErrorType.{{ error.type|title|replace({'_': ''}) }}, '{{ error.type }}');
{% endfor %}

	console.log('All tests passed!');
} catch (error) {
	console.error('Test failed:', error);
}
{% endif %}
