{% if spec.definitions.appwriteException.errorTypes|length > 0 %}
import * as assert from "assert";
import { ErrorType } from "../src/exception.ts"

try {
	{% for error in spec.definitions.appwriteException.errorTypes %}
	assert.strictEqual(ErrorType.{{ error.type|title|replace({'_': ''}) }}, '{{ error.type }}');
    {% endfor %}

	console.log('All tests passed!');
} catch (error) {
	console.error('Test failed:', error);
}
{% endif %}